// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: api/proto/device/v1/device.proto

package devicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Device types
type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	DeviceType_DEVICE_TYPE_MICROPHONE  DeviceType = 1
	DeviceType_DEVICE_TYPE_CAMERA      DeviceType = 2
	DeviceType_DEVICE_TYPE_SCREEN      DeviceType = 3
	DeviceType_DEVICE_TYPE_SPEAKER     DeviceType = 4
	DeviceType_DEVICE_TYPE_KEYBOARD    DeviceType = 5
	DeviceType_DEVICE_TYPE_MOUSE       DeviceType = 6
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_MICROPHONE",
		2: "DEVICE_TYPE_CAMERA",
		3: "DEVICE_TYPE_SCREEN",
		4: "DEVICE_TYPE_SPEAKER",
		5: "DEVICE_TYPE_KEYBOARD",
		6: "DEVICE_TYPE_MOUSE",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_MICROPHONE":  1,
		"DEVICE_TYPE_CAMERA":      2,
		"DEVICE_TYPE_SCREEN":      3,
		"DEVICE_TYPE_SPEAKER":     4,
		"DEVICE_TYPE_KEYBOARD":    5,
		"DEVICE_TYPE_MOUSE":       6,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_device_v1_device_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_api_proto_device_v1_device_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{0}
}

// Device states
type DeviceState int32

const (
	DeviceState_DEVICE_STATE_UNSPECIFIED DeviceState = 0
	DeviceState_DEVICE_STATE_AVAILABLE   DeviceState = 1
	DeviceState_DEVICE_STATE_IN_USE      DeviceState = 2
	DeviceState_DEVICE_STATE_ERROR       DeviceState = 3
	DeviceState_DEVICE_STATE_OFFLINE     DeviceState = 4
)

// Enum value maps for DeviceState.
var (
	DeviceState_name = map[int32]string{
		0: "DEVICE_STATE_UNSPECIFIED",
		1: "DEVICE_STATE_AVAILABLE",
		2: "DEVICE_STATE_IN_USE",
		3: "DEVICE_STATE_ERROR",
		4: "DEVICE_STATE_OFFLINE",
	}
	DeviceState_value = map[string]int32{
		"DEVICE_STATE_UNSPECIFIED": 0,
		"DEVICE_STATE_AVAILABLE":   1,
		"DEVICE_STATE_IN_USE":      2,
		"DEVICE_STATE_ERROR":       3,
		"DEVICE_STATE_OFFLINE":     4,
	}
)

func (x DeviceState) Enum() *DeviceState {
	p := new(DeviceState)
	*p = x
	return p
}

func (x DeviceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_device_v1_device_proto_enumTypes[1].Descriptor()
}

func (DeviceState) Type() protoreflect.EnumType {
	return &file_api_proto_device_v1_device_proto_enumTypes[1]
}

func (x DeviceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceState.Descriptor instead.
func (DeviceState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{1}
}

// Command types
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED   CommandType = 0
	CommandType_COMMAND_TYPE_START         CommandType = 1
	CommandType_COMMAND_TYPE_STOP          CommandType = 2
	CommandType_COMMAND_TYPE_PAUSE         CommandType = 3
	CommandType_COMMAND_TYPE_RESUME        CommandType = 4
	CommandType_COMMAND_TYPE_SET_PARAMETER CommandType = 5
	CommandType_COMMAND_TYPE_GET_PARAMETER CommandType = 6
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_START",
		2: "COMMAND_TYPE_STOP",
		3: "COMMAND_TYPE_PAUSE",
		4: "COMMAND_TYPE_RESUME",
		5: "COMMAND_TYPE_SET_PARAMETER",
		6: "COMMAND_TYPE_GET_PARAMETER",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":   0,
		"COMMAND_TYPE_START":         1,
		"COMMAND_TYPE_STOP":          2,
		"COMMAND_TYPE_PAUSE":         3,
		"COMMAND_TYPE_RESUME":        4,
		"COMMAND_TYPE_SET_PARAMETER": 5,
		"COMMAND_TYPE_GET_PARAMETER": 6,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_device_v1_device_proto_enumTypes[2].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_api_proto_device_v1_device_proto_enumTypes[2]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{2}
}

// Event types
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED          EventType = 0
	EventType_EVENT_TYPE_DEVICE_ADDED         EventType = 1
	EventType_EVENT_TYPE_DEVICE_REMOVED       EventType = 2
	EventType_EVENT_TYPE_DEVICE_STATE_CHANGED EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_DEVICE_ADDED",
		2: "EVENT_TYPE_DEVICE_REMOVED",
		3: "EVENT_TYPE_DEVICE_STATE_CHANGED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":          0,
		"EVENT_TYPE_DEVICE_ADDED":         1,
		"EVENT_TYPE_DEVICE_REMOVED":       2,
		"EVENT_TYPE_DEVICE_STATE_CHANGED": 3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_device_v1_device_proto_enumTypes[3].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_proto_device_v1_device_proto_enumTypes[3]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{3}
}

// Device information
type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          DeviceType             `protobuf:"varint,2,opt,name=type,proto3,enum=device.v1.DeviceType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	State         DeviceState            `protobuf:"varint,5,opt,name=state,proto3,enum=device.v1.DeviceState" json:"state,omitempty"`
	Capabilities  map[string]string      `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RegisteredAt  int64                  `protobuf:"varint,7,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"` // Unix timestamp in nanoseconds
	LastUsedAt    int64                  `protobuf:"varint,8,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`     // Unix timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetType() DeviceType {
	if x != nil {
		return x.Type
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Device) GetState() DeviceState {
	if x != nil {
		return x.State
	}
	return DeviceState_DEVICE_STATE_UNSPECIFIED
}

func (x *Device) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Device) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *Device) GetLastUsedAt() int64 {
	if x != nil {
		return x.LastUsedAt
	}
	return 0
}

// RegisterDevice request
type RegisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DeviceType             `protobuf:"varint,1,opt,name=type,proto3,enum=device.v1.DeviceType" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities  map[string]string      `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterDeviceRequest) GetType() DeviceType {
	if x != nil {
		return x.Type
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *RegisterDeviceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RegisterDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterDeviceRequest) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// RegisterDevice response
type RegisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterDeviceResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// UnregisterDevice request
type UnregisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDeviceRequest) Reset() {
	*x = UnregisterDeviceRequest{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDeviceRequest) ProtoMessage() {}

func (x *UnregisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*UnregisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// UnregisterDevice response
type UnregisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDeviceResponse) Reset() {
	*x = UnregisterDeviceResponse{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDeviceResponse) ProtoMessage() {}

func (x *UnregisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*UnregisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListDevices request
type ListDevicesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by device type (empty = all types)
	FilterType    DeviceType `protobuf:"varint,1,opt,name=filter_type,json=filterType,proto3,enum=device.v1.DeviceType" json:"filter_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{5}
}

func (x *ListDevicesRequest) GetFilterType() DeviceType {
	if x != nil {
		return x.FilterType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

// ListDevices response
type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{6}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

// GetDevice request
type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// GetDevice response
type GetDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceResponse) Reset() {
	*x = GetDeviceResponse{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResponse) ProtoMessage() {}

func (x *GetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

// RequestDeviceAccess request
type RequestDeviceAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDeviceAccessRequest) Reset() {
	*x = RequestDeviceAccessRequest{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDeviceAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeviceAccessRequest) ProtoMessage() {}

func (x *RequestDeviceAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeviceAccessRequest.ProtoReflect.Descriptor instead.
func (*RequestDeviceAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{9}
}

func (x *RequestDeviceAccessRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RequestDeviceAccessRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// RequestDeviceAccess response
type RequestDeviceAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantId       string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	ShmPath       string                 `protobuf:"bytes,2,opt,name=shm_path,json=shmPath,proto3" json:"shm_path,omitempty"`
	UdsPath       string                 `protobuf:"bytes,3,opt,name=uds_path,json=udsPath,proto3" json:"uds_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDeviceAccessResponse) Reset() {
	*x = RequestDeviceAccessResponse{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDeviceAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeviceAccessResponse) ProtoMessage() {}

func (x *RequestDeviceAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeviceAccessResponse.ProtoReflect.Descriptor instead.
func (*RequestDeviceAccessResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{10}
}

func (x *RequestDeviceAccessResponse) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *RequestDeviceAccessResponse) GetShmPath() string {
	if x != nil {
		return x.ShmPath
	}
	return ""
}

func (x *RequestDeviceAccessResponse) GetUdsPath() string {
	if x != nil {
		return x.UdsPath
	}
	return ""
}

// ReleaseDeviceAccess request
type ReleaseDeviceAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseDeviceAccessRequest) Reset() {
	*x = ReleaseDeviceAccessRequest{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseDeviceAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseDeviceAccessRequest) ProtoMessage() {}

func (x *ReleaseDeviceAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseDeviceAccessRequest.ProtoReflect.Descriptor instead.
func (*ReleaseDeviceAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseDeviceAccessRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReleaseDeviceAccessRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// ReleaseDeviceAccess response
type ReleaseDeviceAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseDeviceAccessResponse) Reset() {
	*x = ReleaseDeviceAccessResponse{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseDeviceAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseDeviceAccessResponse) ProtoMessage() {}

func (x *ReleaseDeviceAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseDeviceAccessResponse.ProtoReflect.Descriptor instead.
func (*ReleaseDeviceAccessResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{12}
}

func (x *ReleaseDeviceAccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SubscribeToDevice request
type SubscribeToDeviceRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClientId string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Stream configuration
	Config        *StreamConfig `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToDeviceRequest) Reset() {
	*x = SubscribeToDeviceRequest{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToDeviceRequest) ProtoMessage() {}

func (x *SubscribeToDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToDeviceRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToDeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeToDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SubscribeToDeviceRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SubscribeToDeviceRequest) GetConfig() *StreamConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Stream configuration
type StreamConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Frame format (e.g., "YUYV", "MJPEG", "H264" for video; "S16_LE", "FLOAT" for audio)
	Format string `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	// Resolution for video (e.g., "1920x1080")
	Resolution string `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	// Frame rate for video (e.g., 30, 60)
	FrameRate int32 `protobuf:"varint,3,opt,name=frame_rate,json=frameRate,proto3" json:"frame_rate,omitempty"`
	// Sample rate for audio (e.g., 48000)
	SampleRate int32 `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// Channels for audio (e.g., 1, 2)
	Channels      int32 `protobuf:"varint,5,opt,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamConfig) Reset() {
	*x = StreamConfig{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfig) ProtoMessage() {}

func (x *StreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfig.ProtoReflect.Descriptor instead.
func (*StreamConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{14}
}

func (x *StreamConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *StreamConfig) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *StreamConfig) GetFrameRate() int32 {
	if x != nil {
		return x.FrameRate
	}
	return 0
}

func (x *StreamConfig) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *StreamConfig) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

// Device data frame
type DeviceDataFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Frame sequence number
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Timestamp when frame was captured (Unix nanoseconds)
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Frame data (can be empty if using shared memory)
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Shared memory offset (if using SHM for zero-copy)
	ShmOffset uint64 `protobuf:"varint,4,opt,name=shm_offset,json=shmOffset,proto3" json:"shm_offset,omitempty"`
	// Frame size in bytes
	Size uint32 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	// Frame metadata
	Metadata      map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceDataFrame) Reset() {
	*x = DeviceDataFrame{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDataFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDataFrame) ProtoMessage() {}

func (x *DeviceDataFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDataFrame.ProtoReflect.Descriptor instead.
func (*DeviceDataFrame) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{15}
}

func (x *DeviceDataFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DeviceDataFrame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeviceDataFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DeviceDataFrame) GetShmOffset() uint64 {
	if x != nil {
		return x.ShmOffset
	}
	return 0
}

func (x *DeviceDataFrame) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DeviceDataFrame) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Device command (for bidirectional streaming)
type DeviceCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command type
	Type CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=device.v1.CommandType" json:"type,omitempty"`
	// Command parameters
	Parameters    map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCommand) Reset() {
	*x = DeviceCommand{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCommand) ProtoMessage() {}

func (x *DeviceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCommand.ProtoReflect.Descriptor instead.
func (*DeviceCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{16}
}

func (x *DeviceCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *DeviceCommand) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// WatchDevices request
type WatchDevicesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by device type
	FilterType    DeviceType `protobuf:"varint,1,opt,name=filter_type,json=filterType,proto3,enum=device.v1.DeviceType" json:"filter_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDevicesRequest) Reset() {
	*x = WatchDevicesRequest{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDevicesRequest) ProtoMessage() {}

func (x *WatchDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDevicesRequest.ProtoReflect.Descriptor instead.
func (*WatchDevicesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{17}
}

func (x *WatchDevicesRequest) GetFilterType() DeviceType {
	if x != nil {
		return x.FilterType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

// Device event (for watching device changes)
type DeviceEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type
	Type EventType `protobuf:"varint,1,opt,name=type,proto3,enum=device.v1.EventType" json:"type,omitempty"`
	// Device information
	Device *Device `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	// Old state (for state change events)
	OldState DeviceState `protobuf:"varint,3,opt,name=old_state,json=oldState,proto3,enum=device.v1.DeviceState" json:"old_state,omitempty"`
	// Timestamp of event (Unix nanoseconds)
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceEvent) Reset() {
	*x = DeviceEvent{}
	mi := &file_api_proto_device_v1_device_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceEvent) ProtoMessage() {}

func (x *DeviceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_device_v1_device_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceEvent.ProtoReflect.Descriptor instead.
func (*DeviceEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_device_v1_device_proto_rawDescGZIP(), []int{18}
}

func (x *DeviceEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *DeviceEvent) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *DeviceEvent) GetOldState() DeviceState {
	if x != nil {
		return x.OldState
	}
	return DeviceState_DEVICE_STATE_UNSPECIFIED
}

func (x *DeviceEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_device_v1_device_proto protoreflect.FileDescriptor

const file_api_proto_device_v1_device_proto_rawDesc = "" +
	"\n" +
	" api/proto/device/v1/device.proto\x12\tdevice.v1\"\xea\x02\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.device.v1.DeviceTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12,\n" +
	"\x05state\x18\x05 \x01(\x0e2\x16.device.v1.DeviceStateR\x05state\x12G\n" +
	"\fcapabilities\x18\x06 \x03(\v2#.device.v1.Device.CapabilitiesEntryR\fcapabilities\x12#\n" +
	"\rregistered_at\x18\a \x01(\x03R\fregisteredAt\x12 \n" +
	"\flast_used_at\x18\b \x01(\x03R\n" +
	"lastUsedAt\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\x15RegisterDeviceRequest\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.device.v1.DeviceTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12V\n" +
	"\fcapabilities\x18\x04 \x03(\v22.device.v1.RegisterDeviceRequest.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x16RegisterDeviceResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"6\n" +
	"\x17UnregisterDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"4\n" +
	"\x18UnregisterDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"L\n" +
	"\x12ListDevicesRequest\x126\n" +
	"\vfilter_type\x18\x01 \x01(\x0e2\x15.device.v1.DeviceTypeR\n" +
	"filterType\"B\n" +
	"\x13ListDevicesResponse\x12+\n" +
	"\adevices\x18\x01 \x03(\v2\x11.device.v1.DeviceR\adevices\"/\n" +
	"\x10GetDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\">\n" +
	"\x11GetDeviceResponse\x12)\n" +
	"\x06device\x18\x01 \x01(\v2\x11.device.v1.DeviceR\x06device\"V\n" +
	"\x1aRequestDeviceAccessRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"n\n" +
	"\x1bRequestDeviceAccessResponse\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12\x19\n" +
	"\bshm_path\x18\x02 \x01(\tR\ashmPath\x12\x19\n" +
	"\buds_path\x18\x03 \x01(\tR\audsPath\"V\n" +
	"\x1aReleaseDeviceAccessRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"7\n" +
	"\x1bReleaseDeviceAccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x85\x01\n" +
	"\x18SubscribeToDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.device.v1.StreamConfigR\x06config\"\xa2\x01\n" +
	"\fStreamConfig\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\x12\x1d\n" +
	"\n" +
	"frame_rate\x18\x03 \x01(\x05R\tframeRate\x12\x1f\n" +
	"\vsample_rate\x18\x04 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x05 \x01(\x05R\bchannels\"\x95\x02\n" +
	"\x0fDeviceDataFrame\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"shm_offset\x18\x04 \x01(\x04R\tshmOffset\x12\x12\n" +
	"\x04size\x18\x05 \x01(\rR\x04size\x12D\n" +
	"\bmetadata\x18\x06 \x03(\v2(.device.v1.DeviceDataFrame.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x01\n" +
	"\rDeviceCommand\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.device.v1.CommandTypeR\x04type\x12H\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2(.device.v1.DeviceCommand.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x13WatchDevicesRequest\x126\n" +
	"\vfilter_type\x18\x01 \x01(\x0e2\x15.device.v1.DeviceTypeR\n" +
	"filterType\"\xb5\x01\n" +
	"\vDeviceEvent\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.device.v1.EventTypeR\x04type\x12)\n" +
	"\x06device\x18\x02 \x01(\v2\x11.device.v1.DeviceR\x06device\x123\n" +
	"\told_state\x18\x03 \x01(\x0e2\x16.device.v1.DeviceStateR\boldState\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp*\xbf\x01\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DEVICE_TYPE_MICROPHONE\x10\x01\x12\x16\n" +
	"\x12DEVICE_TYPE_CAMERA\x10\x02\x12\x16\n" +
	"\x12DEVICE_TYPE_SCREEN\x10\x03\x12\x17\n" +
	"\x13DEVICE_TYPE_SPEAKER\x10\x04\x12\x18\n" +
	"\x14DEVICE_TYPE_KEYBOARD\x10\x05\x12\x15\n" +
	"\x11DEVICE_TYPE_MOUSE\x10\x06*\x92\x01\n" +
	"\vDeviceState\x12\x1c\n" +
	"\x18DEVICE_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DEVICE_STATE_AVAILABLE\x10\x01\x12\x17\n" +
	"\x13DEVICE_STATE_IN_USE\x10\x02\x12\x16\n" +
	"\x12DEVICE_STATE_ERROR\x10\x03\x12\x18\n" +
	"\x14DEVICE_STATE_OFFLINE\x10\x04*\xcb\x01\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12COMMAND_TYPE_START\x10\x01\x12\x15\n" +
	"\x11COMMAND_TYPE_STOP\x10\x02\x12\x16\n" +
	"\x12COMMAND_TYPE_PAUSE\x10\x03\x12\x17\n" +
	"\x13COMMAND_TYPE_RESUME\x10\x04\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_SET_PARAMETER\x10\x05\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_GET_PARAMETER\x10\x06*\x88\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EVENT_TYPE_DEVICE_ADDED\x10\x01\x12\x1d\n" +
	"\x19EVENT_TYPE_DEVICE_REMOVED\x10\x02\x12#\n" +
	"\x1fEVENT_TYPE_DEVICE_STATE_CHANGED\x10\x032\x92\x06\n" +
	"\rDeviceService\x12U\n" +
	"\x0eRegisterDevice\x12 .device.v1.RegisterDeviceRequest\x1a!.device.v1.RegisterDeviceResponse\x12[\n" +
	"\x10UnregisterDevice\x12\".device.v1.UnregisterDeviceRequest\x1a#.device.v1.UnregisterDeviceResponse\x12L\n" +
	"\vListDevices\x12\x1d.device.v1.ListDevicesRequest\x1a\x1e.device.v1.ListDevicesResponse\x12F\n" +
	"\tGetDevice\x12\x1b.device.v1.GetDeviceRequest\x1a\x1c.device.v1.GetDeviceResponse\x12d\n" +
	"\x13RequestDeviceAccess\x12%.device.v1.RequestDeviceAccessRequest\x1a&.device.v1.RequestDeviceAccessResponse\x12d\n" +
	"\x13ReleaseDeviceAccess\x12%.device.v1.ReleaseDeviceAccessRequest\x1a&.device.v1.ReleaseDeviceAccessResponse\x12V\n" +
	"\x11SubscribeToDevice\x12#.device.v1.SubscribeToDeviceRequest\x1a\x1a.device.v1.DeviceDataFrame0\x01\x12I\n" +
	"\rDeviceChannel\x12\x18.device.v1.DeviceCommand\x1a\x1a.device.v1.DeviceDataFrame(\x010\x01\x12H\n" +
	"\fWatchDevices\x12\x1e.device.v1.WatchDevicesRequest\x1a\x16.device.v1.DeviceEvent0\x01B=Z;github.com/daoneill/ollama-proxy/api/gen/device/v1;devicev1b\x06proto3"

var (
	file_api_proto_device_v1_device_proto_rawDescOnce sync.Once
	file_api_proto_device_v1_device_proto_rawDescData []byte
)

func file_api_proto_device_v1_device_proto_rawDescGZIP() []byte {
	file_api_proto_device_v1_device_proto_rawDescOnce.Do(func() {
		file_api_proto_device_v1_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_device_v1_device_proto_rawDesc), len(file_api_proto_device_v1_device_proto_rawDesc)))
	})
	return file_api_proto_device_v1_device_proto_rawDescData
}

var file_api_proto_device_v1_device_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_proto_device_v1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_device_v1_device_proto_goTypes = []any{
	(DeviceType)(0),                     // 0: device.v1.DeviceType
	(DeviceState)(0),                    // 1: device.v1.DeviceState
	(CommandType)(0),                    // 2: device.v1.CommandType
	(EventType)(0),                      // 3: device.v1.EventType
	(*Device)(nil),                      // 4: device.v1.Device
	(*RegisterDeviceRequest)(nil),       // 5: device.v1.RegisterDeviceRequest
	(*RegisterDeviceResponse)(nil),      // 6: device.v1.RegisterDeviceResponse
	(*UnregisterDeviceRequest)(nil),     // 7: device.v1.UnregisterDeviceRequest
	(*UnregisterDeviceResponse)(nil),    // 8: device.v1.UnregisterDeviceResponse
	(*ListDevicesRequest)(nil),          // 9: device.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),         // 10: device.v1.ListDevicesResponse
	(*GetDeviceRequest)(nil),            // 11: device.v1.GetDeviceRequest
	(*GetDeviceResponse)(nil),           // 12: device.v1.GetDeviceResponse
	(*RequestDeviceAccessRequest)(nil),  // 13: device.v1.RequestDeviceAccessRequest
	(*RequestDeviceAccessResponse)(nil), // 14: device.v1.RequestDeviceAccessResponse
	(*ReleaseDeviceAccessRequest)(nil),  // 15: device.v1.ReleaseDeviceAccessRequest
	(*ReleaseDeviceAccessResponse)(nil), // 16: device.v1.ReleaseDeviceAccessResponse
	(*SubscribeToDeviceRequest)(nil),    // 17: device.v1.SubscribeToDeviceRequest
	(*StreamConfig)(nil),                // 18: device.v1.StreamConfig
	(*DeviceDataFrame)(nil),             // 19: device.v1.DeviceDataFrame
	(*DeviceCommand)(nil),               // 20: device.v1.DeviceCommand
	(*WatchDevicesRequest)(nil),         // 21: device.v1.WatchDevicesRequest
	(*DeviceEvent)(nil),                 // 22: device.v1.DeviceEvent
	nil,                                 // 23: device.v1.Device.CapabilitiesEntry
	nil,                                 // 24: device.v1.RegisterDeviceRequest.CapabilitiesEntry
	nil,                                 // 25: device.v1.DeviceDataFrame.MetadataEntry
	nil,                                 // 26: device.v1.DeviceCommand.ParametersEntry
}
var file_api_proto_device_v1_device_proto_depIdxs = []int32{
	0,  // 0: device.v1.Device.type:type_name -> device.v1.DeviceType
	1,  // 1: device.v1.Device.state:type_name -> device.v1.DeviceState
	23, // 2: device.v1.Device.capabilities:type_name -> device.v1.Device.CapabilitiesEntry
	0,  // 3: device.v1.RegisterDeviceRequest.type:type_name -> device.v1.DeviceType
	24, // 4: device.v1.RegisterDeviceRequest.capabilities:type_name -> device.v1.RegisterDeviceRequest.CapabilitiesEntry
	0,  // 5: device.v1.ListDevicesRequest.filter_type:type_name -> device.v1.DeviceType
	4,  // 6: device.v1.ListDevicesResponse.devices:type_name -> device.v1.Device
	4,  // 7: device.v1.GetDeviceResponse.device:type_name -> device.v1.Device
	18, // 8: device.v1.SubscribeToDeviceRequest.config:type_name -> device.v1.StreamConfig
	25, // 9: device.v1.DeviceDataFrame.metadata:type_name -> device.v1.DeviceDataFrame.MetadataEntry
	2,  // 10: device.v1.DeviceCommand.type:type_name -> device.v1.CommandType
	26, // 11: device.v1.DeviceCommand.parameters:type_name -> device.v1.DeviceCommand.ParametersEntry
	0,  // 12: device.v1.WatchDevicesRequest.filter_type:type_name -> device.v1.DeviceType
	3,  // 13: device.v1.DeviceEvent.type:type_name -> device.v1.EventType
	4,  // 14: device.v1.DeviceEvent.device:type_name -> device.v1.Device
	1,  // 15: device.v1.DeviceEvent.old_state:type_name -> device.v1.DeviceState
	5,  // 16: device.v1.DeviceService.RegisterDevice:input_type -> device.v1.RegisterDeviceRequest
	7,  // 17: device.v1.DeviceService.UnregisterDevice:input_type -> device.v1.UnregisterDeviceRequest
	9,  // 18: device.v1.DeviceService.ListDevices:input_type -> device.v1.ListDevicesRequest
	11, // 19: device.v1.DeviceService.GetDevice:input_type -> device.v1.GetDeviceRequest
	13, // 20: device.v1.DeviceService.RequestDeviceAccess:input_type -> device.v1.RequestDeviceAccessRequest
	15, // 21: device.v1.DeviceService.ReleaseDeviceAccess:input_type -> device.v1.ReleaseDeviceAccessRequest
	17, // 22: device.v1.DeviceService.SubscribeToDevice:input_type -> device.v1.SubscribeToDeviceRequest
	20, // 23: device.v1.DeviceService.DeviceChannel:input_type -> device.v1.DeviceCommand
	21, // 24: device.v1.DeviceService.WatchDevices:input_type -> device.v1.WatchDevicesRequest
	6,  // 25: device.v1.DeviceService.RegisterDevice:output_type -> device.v1.RegisterDeviceResponse
	8,  // 26: device.v1.DeviceService.UnregisterDevice:output_type -> device.v1.UnregisterDeviceResponse
	10, // 27: device.v1.DeviceService.ListDevices:output_type -> device.v1.ListDevicesResponse
	12, // 28: device.v1.DeviceService.GetDevice:output_type -> device.v1.GetDeviceResponse
	14, // 29: device.v1.DeviceService.RequestDeviceAccess:output_type -> device.v1.RequestDeviceAccessResponse
	16, // 30: device.v1.DeviceService.ReleaseDeviceAccess:output_type -> device.v1.ReleaseDeviceAccessResponse
	19, // 31: device.v1.DeviceService.SubscribeToDevice:output_type -> device.v1.DeviceDataFrame
	19, // 32: device.v1.DeviceService.DeviceChannel:output_type -> device.v1.DeviceDataFrame
	22, // 33: device.v1.DeviceService.WatchDevices:output_type -> device.v1.DeviceEvent
	25, // [25:34] is the sub-list for method output_type
	16, // [16:25] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_device_v1_device_proto_init() }
func file_api_proto_device_v1_device_proto_init() {
	if File_api_proto_device_v1_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_device_v1_device_proto_rawDesc), len(file_api_proto_device_v1_device_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_device_v1_device_proto_goTypes,
		DependencyIndexes: file_api_proto_device_v1_device_proto_depIdxs,
		EnumInfos:         file_api_proto_device_v1_device_proto_enumTypes,
		MessageInfos:      file_api_proto_device_v1_device_proto_msgTypes,
	}.Build()
	File_api_proto_device_v1_device_proto = out.File
	file_api_proto_device_v1_device_proto_goTypes = nil
	file_api_proto_device_v1_device_proto_depIdxs = nil
}
